
language: node_js
node_js:
  - '8' # EOL: December 2019
  # Please enable these matrix values after bug #228 is fixed
  #- '10' # EOL: April 2021
  #- '11' # EOL: June 2019

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.electron-gyp

matrix:
  fast_finish: true
  allow_failures:
    - os: windows
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.2
    - os: windows
      env: YARN_GPG=no # Travis-CI Bug: gpg-agent hangs build task in windows
      cache: false     # Travis-CI Bug: cache stage fails to mount in windows

# Use Yarn stable version 1.17.3 instead of Travis CI default 1.3.2
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
# Workaround for Network connection errors
  - yarn config delete proxy
  - npm config rm proxy
  - npm config rm https-proxy
  - yarn config set network-timeout 1000000

install:
  - travis_retry yarn --frozen-lockfile --non-interactive --check-files --network-timeout 100000

script:
  - yarn run rebuild-leveldb
  - yarn run lint
  - yarn run build
  - yarn run dist

deploy:
  provider: script
  script: yarn run dist
  on:
    all_branches: true
  skip_cleanup: true
  file_glob: true
  file: "dist/Mapeo-darwin-x64/Installar_Mapeo*.dmg"
  api_key:
    secure: drFLl3ufKFIUyAdGDDtW8ddpEb75JydIpWobEMnIg+BlbsqdBree3AhuqkBJbO/gnyqs3XQp3tCMmsgCSj2hDVCNW0hsJ+lTzdLM0xpc85IRIYCAMf+x/4H2qIziwqNtxNI44Zuz2wVpwRmAC65mr8MqMsXqxe9ZO2udNdx/ofpkngvczHbcoYl2mhgmQPwtpV/YfVOWVtxTM0qF9zgfNdfRv/+tV44mU66ibXEgV3Lefco4TvmgAdlehwzD+tL36Idg1J4jgbnm+GK9iyhN3MO5RnUTT3mVK4gy2ovE/s3+tLSm98XdAo5+7NyqR8PwnLbuUHSpMX84jlp8vJ+vL2NvedQtCACu1LDB5pzc+vM7rf7K4B5N48VC8RYfMUUb/qtCylWd8QdqwSuSpxPV1beuWZOi7dwf03UAPjRhqGg+ATNisiyT8GnkhEg+z6AAV+dWz/dT1I6EbeotIOciy0HJ1wdCWbBve68W2aaDUSRsEOURi1YE/TYLZt77swjBHUbOrpz/udFp/Q93NH+RYlkh52VrCJ7K2KuLMLCSwsuR1IyK1e8kSCXZplph9YbZJzkk2D9hwV6SJX9vw+vmKBqz2gb02JNDmGxHVnvTZFw5U+1dzWAlMyqC+cqOBY0C668BFDJPZ/uJWDqoU+2FU0dLXx2XY7UBoup5pJUdFdw=
